
environment:

    matrix:
        # The package name
        - PACKAGE: "DebugTools"
          SUBLIME_TEXT_VERSION : "3"

        - TOXENV: py27
        - TOXENV: py33
        - TOXENV: py34
        - TOXENV: py35
        - TOXENV: py36


install:
    - IF NOT "%TOXENV%"=="" (C:\Python27\python -m pip install --pre -U tox)

    - ps: If(!$env:toxenv) {appveyor DownloadFile "https://raw.githubusercontent.com/evandroforks/UnitTesting/master/sbin/appveyor.ps1"}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "bootstrap" -verbose}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "clone_git_package" "https://github.com/evandroforks/PortalockerFiles" "PortalockerFiles" -verbose}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "clone_git_package" "https://github.com/evandroforks/ConcurrentLogHandler" "ConcurrentLogHandler" -verbose}
    - ps: If(!$env:toxenv) {pip install coverage codacy-coverage}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "install_package_control" -verbose}


build: off


test_script:
    - IF NOT "%TOXENV%"=="" (C:\Python27\scripts\tox)
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "run_tests" -coverage -verbose}


on_finish:
    - IF "%TOXENV%"=="" (SET PYTHON=C:\\Python33)
    - IF "%TOXENV%"=="" (SETLOCAL ENABLEDELAYEDEXPANSION && SET PATH=!PYTHON!;!PYTHON!\\Scripts;!PATH!)
    - IF "%TOXENV%"=="" (pip install codecov)
    - IF "%TOXENV%"=="" (codecov)
    - IF "%TOXENV%"=="" (python --version)
    - IF "%TOXENV%"=="" (SETLOCAL ENABLEDELAYEDEXPANSION && echo !PATH!)
    - IF "%TOXENV%"=="" (coverage xml -o coverage.xml)
    - IF "%TOXENV%"=="" (python-codacy-coverage)

