
environment:

    matrix:
        # The package name
        - PACKAGE: "DebugTools"
          SUBLIME_TEXT_VERSION : "3"

        - TOXENV: py27
        - TOXENV: py34
        - TOXENV: py35
        - TOXENV: py36


install:
    - python --version
    - dir
    - pip list
    - IF NOT "%TOXENV%"=="" (C:\Python27\python -m pip install --disable-pip-version-check --pre -U tox)
    - IF NOT "%TOXENV%"=="" (pip install --disable-pip-version-check -e .[full])
    - IF NOT "%TOXENV%"=="" (pip install --disable-pip-version-check diff-match-patch)
    - IF NOT "%TOXENV%"=="" (pip install --disable-pip-version-check diff_match_patch)
    - IF "%TOXENV%"=="" (pip install --disable-pip-version-check codecov)
    - IF "%TOXENV%"=="" (pip install --disable-pip-version-check codacy-coverage)
    - IF "%TOXENV%"=="" (pip install --disable-pip-version-check python-coveralls)
    - choco install codecov

    - ps: If(!$env:toxenv) {pip install --disable-pip-version-check coverage codacy-coverage python-coveralls}
    - ps: If(!$env:toxenv) {appveyor DownloadFile "https://raw.githubusercontent.com/evandroforks/UnitTesting/master/sbin/appveyor.ps1"}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "bootstrap" -verbose}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "clone_git_package" "https://github.com/evandroforks/PortalockerFiles" "PortalockerFiles" -verbose}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "clone_git_package" "https://github.com/evandroforks/DiffMatchPatch" "DiffMatchPatch" -verbose}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "clone_git_package" "https://github.com/evandroforks/ConcurrentLogHandler" "ConcurrentLogHandler" -verbose}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "clone_git_package" "https://github.com/evandroforks/python-pywin32" "python-pywin32" -verbose}
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "install_package_control" -verbose}
    - pip list


build: off


test_script:
    - IF NOT "%TOXENV%"=="" (C:\Python27\scripts\tox)
    - ps: If(!$env:toxenv) {.\appveyor.ps1 "run_tests" -coverage -verbose}


on_finish:
    - IF "%TOXENV%"=="" (SET PYTHON=C:\\Python33)
    - IF "%TOXENV%"=="" (SETLOCAL ENABLEDELAYEDEXPANSION && SET "PATH=!PYTHON!;!PYTHON!\\Scripts;!PATH!")
    - IF "%TOXENV%"=="" (python --version)
    - IF "%TOXENV%"=="" (SETLOCAL ENABLEDELAYEDEXPANSION && echo !PATH!)
    - IF "%TOXENV%"=="" (coverage xml -o coverage.xml)
    - IF "%TOXENV%"=="" (codecov -f coverage.xml)
    - IF "%TOXENV%"=="" (coveralls)
    - IF "%TOXENV%"=="" (python-codacy-coverage)

