
environment:

    matrix:
        - TOXENV: py26
        - TOXENV: py27
        - TOXENV: py33
        - TOXENV: py34
        - TOXENV: py35
        - TOXENV: py36


install:
    - C:\Python27\python -m pip install --pre -U tox


build: off


test_script:
    - C:\Python27\scripts\tox

